[provider]
node = "20.9.0"

[phases.install]
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = ["npm", "run", "start"]

[variables]
NODE_VERSION = "20.9.0"
NODE_ENV = "production"
